telegram:
  token: YOUR_ACCESS_TOKEN

rateApi:
  key: YOUR_API_KEY
  host: YOUR_API_HOST

database:
  host: YOUR_HOST
  port: YOUR_PORT
  username: YOUR_USERNAME
  password: YOUR_PASSWORD

cache:
  host: YOUR_HOST
  port: YOUR_PORT
  username: YOUR_USERNAME
  password: YOUR_PASSWORD

broker:
  - '<HOST>:<PORT>'