version: '3.8'
services:
  db:
    image: postgres:15-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/alerts.yml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./metrics/data:/var/lib/grafana
    links:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # web
      - 14268:14268
      - 9411:9411

  redis:
    image: redis:7.0.5-bullseye
    ports:
      - 6379:6379
    volumes:
      - ./.redis-data:/data

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "reports:3:1" # почитать про топик
    depends_on:
      - zookeeper
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    