// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/callbacks/incoming_clb.go

// Package mock_callbacks is a generated GoMock package.
package mock_callbacks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessageSender) SendMessage(ctx context.Context, text string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, text, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageSenderMockRecorder) SendMessage(ctx, text, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageSender)(nil).SendMessage), ctx, text, userID)
}

// MockUserManipulator is a mock of UserManipulator interface.
type MockUserManipulator struct {
	ctrl     *gomock.Controller
	recorder *MockUserManipulatorMockRecorder
}

// MockUserManipulatorMockRecorder is the mock recorder for MockUserManipulator.
type MockUserManipulatorMockRecorder struct {
	mock *MockUserManipulator
}

// NewMockUserManipulator creates a new mock instance.
func NewMockUserManipulator(ctrl *gomock.Controller) *MockUserManipulator {
	mock := &MockUserManipulator{ctrl: ctrl}
	mock.recorder = &MockUserManipulatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManipulator) EXPECT() *MockUserManipulatorMockRecorder {
	return m.recorder
}

// SetCode mocks base method.
func (m *MockUserManipulator) SetCode(ctx context.Context, userID int64, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCode", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCode indicates an expected call of SetCode.
func (mr *MockUserManipulatorMockRecorder) SetCode(ctx, userID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCode", reflect.TypeOf((*MockUserManipulator)(nil).SetCode), ctx, userID, code)
}

// MockReportCacher is a mock of ReportCacher interface.
type MockReportCacher struct {
	ctrl     *gomock.Controller
	recorder *MockReportCacherMockRecorder
}

// MockReportCacherMockRecorder is the mock recorder for MockReportCacher.
type MockReportCacherMockRecorder struct {
	mock *MockReportCacher
}

// NewMockReportCacher creates a new mock instance.
func NewMockReportCacher(ctrl *gomock.Controller) *MockReportCacher {
	mock := &MockReportCacher{ctrl: ctrl}
	mock.recorder = &MockReportCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCacher) EXPECT() *MockReportCacherMockRecorder {
	return m.recorder
}

// RemoveFromAll mocks base method.
func (m *MockReportCacher) RemoveFromAll(ctx context.Context, key []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromAll", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromAll indicates an expected call of RemoveFromAll.
func (mr *MockReportCacherMockRecorder) RemoveFromAll(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromAll", reflect.TypeOf((*MockReportCacher)(nil).RemoveFromAll), ctx, key)
}
